[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo =  'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Shougo/vinarise'

[[plugins]]
repo = 'ghifarit53/tokyonight-vim'

[[plugins]]
repo='glepnir/oceanic-material'

[[plugins]]
repo='dense-analysis/ale'

[[plugins]]
repo='roxma/vim-hug-neovim-rpc'

[[plugins]]
repo='roxma/nvim-yarp'

[[plugins]]
repo='Shougo/defx.nvim'

[[plugins]]
repo='kristijanhusak/defx-git'

[[plugins]]
repo='kristijanhusak/defx-icons'

[[plugins]]
repo='ryanoasis/vim-devicons'

[[plugins]]
repo='vim-denops/denops.vim'

[[plugins]]
repo='vim-denops/denops-helloworld.vim'

[[plugins]]
repo='Shougo/ddu.vim'

[[plugins]]
repo='Shougo/ddu-ui-ff'

[[plugins]]
repo='Shougo/ddu-source-file_rec'

[[plugins]]
repo='Shougo/ddu-filter-matcher_substring'

[[plugins]]
repo='Shougo/ddu-kind-file'

[[plugins]]
repo='Shougo/ddu-source-file'

[[plugins]]
repo='Shougo/ddu-source-register'

[[plugins]]
repo='kuuote/ddu-source-mr'

[[plugins]]
repo='lambdalisue/mr.vim'

[[plugins]]
repo='shun/ddu-source-buffer'

[[plugins]]
repo='Shougo/ddu-commands.vim'
