[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo =  'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Shougo/vinarise'

[[plugins]]
repo = 'ghifarit53/tokyonight-vim'

[[plugins]]
repo='glepnir/oceanic-material'

[[plugins]]
repo='dense-analysis/ale'

[[plugins]]
repo='roxma/vim-hug-neovim-rpc'

[[plugins]]
repo='roxma/nvim-yarp'

[[plugins]]
repo='Shougo/defx.nvim'
