[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'

[[plugins]]
repo = "thinca/vim-quickrun"

[[plugins]]
repo = 'Shougo/vimproc'

[[plugins]]
repo =  'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'cohama/vim-hier'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo =  'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Shougo/vinarise'

[[plugins]]
repo = 'ghifarit53/tokyonight-vim'
